### ISSUE TITLE
User can create a post

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User may upload an image and write a title and description respective to what they are seeking. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-22 at 3 54 38 PM](https://user-images.githubusercontent.com/85080021/147167849-2b8d0fee-74a5-4c2d-aea0-8e7ff6b59363.png)

![Screen Shot 2021-12-22 at 3 56 27 PM](https://user-images.githubusercontent.com/85080021/147167927-6b3a771c-67d5-4825-9d45-3354821903f9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create schema "session"
- [x] in schema.sql create table for "users"
- [x] in schema.sql create table for "posts"
- [x] Update `data.sql` to insert user info into users table
- [x] Update `data.sql` to insert user posts info into posts table

### ☁️ Server

- [x] Update `server/index.js` to send post request for creating post
- [x] create uploads middleware
- [x] create error middleware
- [x] create json middleware
- [x] throw error if any field is missing
- [x] query database to insert values
- [x] catch any errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render form
- [x] Update form component to accept a form and update state with the values
- [x] Create ref for image uploads
- [x] include event handlers for form values changing and submitting form
- [x] send fetch request with the FormData in the body
- [x] reset form values

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
