### ISSUE TITLE
User can view their own posts

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their own posts
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click or tap on "my account". From there they may click or tap on my posts to view a list of posts they have made.
## 🖼️ Wireframes
![Screen Shot 2022-02-23 at 10 05 07 PM](https://user-images.githubusercontent.com/85080021/155467500-55c59e97-d189-4900-871c-a582a8675508.png)
![Screen Shot 2022-02-23 at 10 05 48 PM](https://user-images.githubusercontent.com/85080021/155467511-4b0d47a7-8fa6-4e1f-80c6-c5243964b184.png)
![Screen Shot 2022-02-23 at 10 05 57 PM](https://user-images.githubusercontent.com/85080021/155467524-c6ba8ac7-ae27-4e4a-b750-f8783c14e329.png)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle GET request
- [x] GET all columns from the posts table where the userId matches the current user's ID.
- [x] Test with HTTPie
- [x] Update payload object to remove the outer "user" object.
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render a list of the users posts.
- [x] Update "account" view component to hide sign-out button when in desktop view
- [x] Send fetch to retrieve the users posts. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
