### ISSUE TITLE
User can sign in

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user clicks or taps on any post, they will be re-directed to the sign in page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-29 at 1 09 37 PM](https://user-images.githubusercontent.com/85080021/147703685-4abbab69-3d86-447f-a899-7708f0104da1.png)
![Screen Shot 2021-12-29 at 1 09 57 PM](https://user-images.githubusercontent.com/85080021/147703689-f84cc9ce-233a-4509-b3ff-236373ce3182.png)
![Screen Shot 2021-12-29 at 1 10 15 PM](https://user-images.githubusercontent.com/85080021/147703696-729a97b4-e525-45ce-8ec9-8bf55ce3c3c7.png)
![Screen Shot 2021-12-29 at 1 10 24 PM](https://user-images.githubusercontent.com/85080021/147703700-473314c5-8c95-476f-b6c4-accf09110bbb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get requests to /api/sessions
- [x] If no username or password throw error
- [x] hash the password
- [x] check to see if it matches the hashed password in the db
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] create component for sign in page
- [x] create form for username and password input
- [x] send fetch with input to server to hash password

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
