### ISSUE TITLE
User can sign up

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user clicks or taps sign in and do not have an account, they can click the link directing them to sign up form
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-01-06 at 2 40 52 PM](https://user-images.githubusercontent.com/85080021/148462538-fa5a819c-ea13-4398-8020-31cc70d3a480.png)
![Screen Shot 2022-01-06 at 2 41 06 PM](https://user-images.githubusercontent.com/85080021/148462543-b3e41ce7-ed1e-4edb-ad76-30c6a804f2eb.png)
![Screen Shot 2022-01-06 at 2 41 44 PM](https://user-images.githubusercontent.com/85080021/148462551-14445ceb-5a60-417c-807d-8c809dc223f2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle POST
- [x] Insert username, hashedPassword, and email into users table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render sign up form
- [x] Update sign-in component to to include link that directs users to sign up page
- [x] update hash
- [x] once user successfully creates account, redirect hash to sign in page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
