### ISSUE TITLE
User can sign out

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Desktop, user clicks sign out in top right hand corner and is redirected to sign in page
mobile, the user clicks the user Icon and taps sign out. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-06 at 3 58 00 PM](https://user-images.githubusercontent.com/85080021/148469123-87416b97-f0c5-4e89-b7e6-4d1a355845b0.png)
![Screen Shot 2022-01-06 at 3 56 57 PM](https://user-images.githubusercontent.com/85080021/148469129-dc4e359c-627a-4388-bbc1-10d6990952bd.png)

![Screen Shot 2022-01-06 at 3 57 18 PM](https://user-images.githubusercontent.com/85080021/148469144-951a919d-b9bf-4a87-b591-c3f28e93a074.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update drawer.jsx component to change button from "sign in" to "sign out"
- [x] If user is signed in, add user to state
- [x] Pass user as props to drawer.jsx
- [x] If there is a user, button text says "sign out"
- [x] If user clicks sign out set user to null
- [x] remove token from local storage
- [x] Change button text to "sign in"
- [x] In mobile, create component to render sign out button if user taps user icon

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
