### ISSUE TITLE
user can view post details

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can view details of a post
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when user taps or clicks on a post a new page will appear containing post details
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-28 at 10 44 15 AM](https://user-images.githubusercontent.com/85080021/147597229-f4a96378-6c80-4581-b06d-48c448658411.png)
![Screen Shot 2021-12-28 at 10 44 43 AM](https://user-images.githubusercontent.com/85080021/147597231-98c2ab4d-c7b1-4a2d-9dc5-eb6ffc43f04c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get request
- [x] request sent to /api/sessions/postId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the details page
- [x] Update component to find the matching postId number of the clicked post
- [x] send fetch request to /api/sessions/postId
- [x] render page with details from that postId number

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
