### ISSUE TITLE
User can view the marketplace

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of posts and tap or click on one to see the details
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can tap or click a post to see the details of the session
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-27 at 9 43 12 AM](https://user-images.githubusercontent.com/85080021/147495390-546e1065-5efc-468c-b149-15d8273cea64.png)

![Screen Shot 2021-12-27 at 9 43 30 AM](https://user-images.githubusercontent.com/85080021/147495415-6c82afc1-bf16-4d32-93c4-5e7b7ef66e20.png)

![Screen Shot 2021-12-27 at 9 43 42 AM](https://user-images.githubusercontent.com/85080021/147495419-10311ea2-9745-40ed-9cb8-c9afb1718e63.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get request to posts
- [x] Query database to receive all posts
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render marketplace view
- [x] Create a component to open app drawer on desktop
- [x] Create a component for icons on mobile
- [x] Add hash route so user may create a new post or view the marketplace
- [x] send fetch request to receive and render post data for cards

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
