### ISSUE TITLE
User can message artist

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#24]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send message to artist
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user clicks or taps message artist, They are directed to the chatroom and may message artist
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-04 at 3 17 25 PM](https://user-images.githubusercontent.com/85080021/148136899-fa43a3a5-b552-42ab-8070-0a0ae5a5e6e9.png)
![Screen Shot 2022-01-04 at 3 17 34 PM](https://user-images.githubusercontent.com/85080021/148136890-4753d5f5-ab33-4fcf-8281-441308400258.png)

![Screen Shot 2022-01-04 at 3 17 06 PM](https://user-images.githubusercontent.com/85080021/148136912-89a5d36a-90bb-4442-9d67-f0628dc1aa50.png)
![Screen Shot 2022-01-04 at 3 17 13 PM](https://user-images.githubusercontent.com/85080021/148136915-3a24d2f3-5d08-4154-a322-c5ee7ea4e57a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Check if user has connected to websockets
- [x] Update `server/index.js` to create chat room between buyer and seller
- [x] Update db with new messages
- [x] Server sends new message to socket chat room
- [x] Respond to the client that sent POST
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update hash route
- [x] Update component post details to add a "message artist" button
- [x] Listen for .on('message') in componentDidMount
- [x] Concatenate new message with with state array

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
