### ISSUE TITLE
User can make an offer

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send an offer for a session
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User may click or tap make an offer, a modal will pop up asking for the offer amount, user can either send an offer or cancel
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-28 at 1 27 46 PM](https://user-images.githubusercontent.com/85080021/147608384-72b2f4f9-62eb-4c2b-a168-cbc91aeb7dd2.png)
![Screen Shot 2021-12-28 at 1 27 52 PM](https://user-images.githubusercontent.com/85080021/147608387-a2384445-adeb-4cb5-9c57-fafa853bf424.png)
![Screen Shot 2021-12-28 at 1 27 58 PM](https://user-images.githubusercontent.com/85080021/147608392-ad91e4f4-2292-4e08-bb43-ac53b5d28fa9.png)
![Screen Shot 2021-12-28 at 1 28 10 PM](https://user-images.githubusercontent.com/85080021/147608400-a9d10604-5d33-4037-a9cc-52424953d09b.png)

![Screen Shot 2021-12-28 at 1 28 18 PM](https://user-images.githubusercontent.com/85080021/147608413-83e43105-c718-47bd-9b36-b54ab854d611.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to accept a message with userId and postId

### ☁️ Server

- [x] Update `server/index.js` to handle POST request to send message (offer)
- [x] query database to insert message into messages table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add 'send an offer' button
- [x] if button is clicked or tapped show modal
- [x] add input form to modal to accept an offer amount
- [x] send POST fetch to server to add message to db

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
