### ISSUE TITLE
User can view offers

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view offers
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User may click or tap on inbox to view offers sent to them 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-29 at 12 56 55 PM](https://user-images.githubusercontent.com/85080021/147702887-62964185-ff89-457b-9a32-a497ce816971.png)
![Screen Shot 2021-12-29 at 12 57 07 PM](https://user-images.githubusercontent.com/85080021/147702889-69240dff-4a6c-45f9-9add-9e874ebb647e.png)
![Screen Shot 2021-12-29 at 12 57 20 PM](https://user-images.githubusercontent.com/85080021/147702895-6a96afc7-2150-4a5a-b432-2ba626d335ff.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get request for messages
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update hash route
- [x] Create a component to render message thread
- [x] Update component to show userName and message
- [x] Add button to direct user to post details on desktop

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
