### ISSUE TITLE
User can reply to offers

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can reply to offers
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User may send offer or message to artist and artist can reply
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-03 at 11 01 07 AM](https://user-images.githubusercontent.com/85080021/147969285-0c894b04-dbf3-4df9-b10b-7917876d3c9c.png)
![Screen Shot 2022-01-03 at 11 01 14 AM](https://user-images.githubusercontent.com/85080021/147969290-032cbcef-28b2-4b6b-95ad-f9f27b6c4b1e.png)
![Screen Shot 2022-01-03 at 11 01 25 AM](https://user-images.githubusercontent.com/85080021/147969311-183afd59-9b87-4fd7-b05f-a89a19099a9d.png)
![Screen Shot 2022-01-03 at 11 01 32 AM](https://user-images.githubusercontent.com/85080021/147969319-f492860a-5ec7-404b-865a-160a1d41542d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` handle post request to messages db
- [x] Insert replies from seller to buyer 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Set up socket connection in componentDidMount
- [x] Update component to render replies in message thread

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
