### ISSUE TITLE
User can view inbox

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view messages in their inbox
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user clicks or taps on inbox, they can view a list of users who sent them messages
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-30 at 11 48 56 AM](https://user-images.githubusercontent.com/85080021/147783916-ffbd4543-7c0c-458f-b6f1-7a178480f33f.png)
![Screen Shot 2021-12-30 at 11 52 17 AM](https://user-images.githubusercontent.com/85080021/147783931-bd49c60f-0d4c-4837-b5db-d8d83f721e05.png)
![Screen Shot 2021-12-30 at 11 52 27 AM](https://user-images.githubusercontent.com/85080021/147783945-5b68d38c-8dd3-4a7c-9808-60ab9fd9cb46.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get requests to messages
- [x] get userName, img, and message content from tables users, and posts
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render inbox view
- [x] Update component to show username, message preview and img for the respective post
- [x] update icons.jsx to switch routes for inbox

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
