### ISSUE TITLE
User can save post 

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a post to favorites
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click or tap the heart Icon to save post to favorites
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-01-07 at 11 44 25 AM](https://user-images.githubusercontent.com/85080021/148599103-c9ee04c1-1787-44c5-a6d7-309983d1651b.png)

![Screen Shot 2022-01-07 at 11 44 46 AM](https://user-images.githubusercontent.com/85080021/148599155-a0ff85a6-1ded-4b67-b87e-8fc53701b0a3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle POST request to saved table
- [x] Update PostDetails GET route to include boolean if user saved post or not
- [x] Insert postId and userId of user who saved post
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update PostDetails component to show heart icon
- [x] toggle with red heart if user clicks icon

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
