### ISSUE TITLE
User can view saved posts

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/session-lite#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view saved posts
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User may click or tap on "saved" or the heart icon and be directed to a new page containing a list of their saved posts
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="937" alt="Screen Shot 2022-02-17 at 5 42 37 PM" src="https://user-images.githubusercontent.com/85080021/154601633-f09c31b3-de16-4e76-8f34-f34107fb2449.png">
<img width="941" alt="Screen Shot 2022-02-17 at 5 42 45 PM" src="https://user-images.githubusercontent.com/85080021/154601650-fb120e8a-d2f1-408d-8d36-6418811a33c9.png">
<img width="384" alt="Screen Shot 2022-02-17 at 5 43 04 PM" src="https://user-images.githubusercontent.com/85080021/154601658-21e954fb-c006-43bf-9e3d-e4ecb063279c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle GET request for posts that user has saved
- [x] Test with HTTPie 
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add anchor to app drawer to direct user to "saved" component
- [x] Add anchor to heart icon to direct user to "saved" component
- [x] Create a component to display users saved posts
- [x] Update component to direct user to post details if clicked

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
